### ISSUE TITLE
Load another Mujoco XML fIle

### ISSUE THREAD

**Issue by YandongJi** [raisimTech/raisimLib#140] opened 2021-07-11 15:43 UTC
HI Jemin thanks for the great work!

When I load another Mujoco xml file by adjusting cassie.cpp, the model does not appear in RaisimUnity and all position and velocity values on the right side of the panel are NaN. I guess it has something to do with Mujoco xml description.

In current Cassie file:
```
<geom type='capsule' size='0.04' fromto='0 0 0 0.43476 0.02 0' class='collision-left'/>
<geom type='box' size='0.1 0.1 0.1' mass='3' class='obstacle'/>
<body name='left-hip-roll' pos='0.021 0.135 0' xyaxes='0 0 -1 0 1 0'>
```

In another Mujoco model file:
```
<geom type='capsule' size ='0.9 0.9' pos='0.9 0 0' euler='8 90 8' class='collision'/>
<geom type='box' size='0.9 0.9 0.9' pos='0.9 0.9 0.9' euler='0 0 0' class='collision'/>
<geom type='cylinder' size ='0.9 0.9' pos='0.9 0 0'  euler='0 0 0' class='collision'/>
<body name='base' pos='0 0 0' **euler**='0 0 0'>
```
I didn't see any cylinder description in Cassie model so I added ours here. Could you check it?

**Comment by jhwangbo** [comment] 2021-07-12 00:47
I think the issue is the collision type and contype and conaffinity. MuJoCo uses "and" convention. Which means that 
``collide if (ob1->contype & ob2->conaffinity && ob2->contype & ob1->conaffinity)``
RaiSim uses "or" convention
``collide if (ob1->contype & ob2->conaffinity || ob2->contype & ob1->conaffinity)``
So you have to adjust them accordingly

**Comment by YandongJi** [comment] 2021-07-17 08:12
Hi Jemin we have the following problems when importing the model:
        - Joints have the same rotation direction.
        - Orientation of collision bodies does not align with orientation of the actual body.
I sent an email to you which is attached with some screenshots and could you check it? thx.

**Comment by jhwangbo** [comment] 2021-07-17 08:23
I figure out the issue. I forgot to implement euler angles when reading the body orientation. I'll fix it and push an update

**Comment by YandongJi** [comment] 2021-07-17 08:30
Great, thx!

**Comment by jhwangbo** [comment] 2021-07-17 10:59
Euler angle was one of the issues. But I don't think that's not what caused the problem. I will push the euler angle fix but I cannot guarantee that this will work for you unless you share the urdf.

**Comment by YandongJi** [comment] 2021-09-07 00:11
The value in the right side panel shows NaN when the joint configuration of Cassie is initialized by the file [attached.](https://drive.google.com/drive/folders/19DP3CgX1kccyVedS4cXNG43qezCcKs6I?usp=sharing) But the simulation runs well when initialized by cassie->setBasePos({0,0,1.0});

**Comment by YandongJi** [comment] 2021-09-12 19:19
Hi Jemin I'm just checking that how difficult to implement this :)

**Comment by jhwangbo** [comment] 2021-09-17 07:40
> The value in the right side panel shows NaN when the joint configuration of Cassie is initialized by the file attached. But the simulation runs well when initialized by cassie->setBasePos({0,0,1.0});

I tried your code and it gives me "Wrong number of generalized coordinate elements" error.

**Comment by YandongJi** [comment] 2021-09-18 04:45
It's so weird that I don't have this error.....
Could you also check the email on Sep 6? I attached some details of our MuJoCo XML model.

**Comment by YandongJi** [comment] 2021-09-25 05:13
Jemin I'm still struggling on this ...... and looking forward to any update. :)

**Comment by jhwangbo** [comment] 2021-09-25 05:14
Yes, i confirmed the bug. I am currently on holidays. I can start checking this next week

**Comment by YandongJi** [comment] 2021-09-25 05:17
Great, thx. Have a great holiday! :)

**Comment by jhwangbo** [comment] 2021-09-28 05:22
It's now working on my local version. There was an uninitialized variable.
I have another issue with your code. If I set the GC as you did, the position constraints are not satisfied. You should start in a state compliant with your constraint. Is this intended?

**Comment by YandongJi** [comment] 2021-09-28 05:40
Have you tried changing the orientation to 1.0, 0, 0, 0 ? I made a mistake here

**Comment by YandongJi** [comment] 2021-09-28 06:12
I can't find a difference compared with [this](https://github.com/osudrl/cassie-mujoco-sim/blob/1ab45636641a8d0404e4118273f3949f39997cd6/src/cassiemujoco.c#L713). Is it possible not to initialize the rod since their relative positions are constrained?

**Comment by jhwangbo** [comment] 2021-09-28 06:39
The pin constraint constrains the relative position but does not say which one can move. For us, it is clear that the rod should move but not for a computer...

It seems like there is a convention error. I'll investigate on this further

**Comment by YandongJi** [comment] 2021-10-02 07:39
![Cassie_view](https://user-images.githubusercontent.com/33598269/135707957-aa80a8f2-40d4-4629-a527-6b9e1b17839a.png)
Jemin the initial configuration looks like this in MuJoCo environment. :)

**Comment by jhwangbo** [comment] 2021-10-04 04:42
ok, I found the difference. I forgot to implement ``ref`` attribute of the joint.

**Comment by jhwangbo** [comment] 2021-10-04 13:27
The fix has been pushed for the linux version. The pin joint is still experimental. Let me know if you find any issues

**Comment by YandongJi** [comment] 2021-10-04 16:16
Thank you. 

Here is one issue. Seems like that the value in the right panel shows NaN after [adding PD gains](https://drive.google.com/file/d/1oH8xOuCfLHklI-gklcNEVTVP1dQ4fSMF/view?usp=sharing).

**Comment by jhwangbo** [comment] 2021-10-04 21:49
I got that code working after initializing ``jointVelocityTarget`` to zero.

https://user-images.githubusercontent.com/3340750/135929419-5d0ef166-1cc7-43ba-bf6e-9cf31c1ede54.mp4

I'll check the other model soon

**Comment by jhwangbo** [comment] 2021-10-05 01:47
Can I share the digit files? You shared it publicly but I am not sure if it is a mistake.

I figured out the issue and the xml file works fine on my machine.

**Comment by YandongJi** [comment] 2021-10-05 01:51
A mistake... sorry I will change the access.

**Comment by jhwangbo** [comment] 2021-10-05 11:58
the angle error fix has been pushed

**Comment by jhwangbo** [comment] 2021-10-07 04:04
1. currently ``getSpring`` method is protected. I'll make it public and push the change tonight
2. I spot two errors in your code. First, you should initialize the base components for PD gains to zeros. Second, you should keep the pd gains for the unactuated joints (e.g., rod) to zero

**Comment by YandongJi** [comment] 2021-10-07 04:27
I didn't see any parts that can set a new spring stiffness, will that be public too?

**Comment by YandongJi** [comment] 2021-10-07 04:32
I mean the function to change the spring stiffness. Sorry for the ambiguity.

**Comment by jhwangbo** [comment] 2021-10-07 04:35
All compliances in the mjcf files will be converted to ``SpringElements``. ``getSpring`` will return non-const ref of them. You can do whatever you want to do with it.

**Closed** 2021-10-08 17:10 UTC
