### ISSUE TITLE
RaisimUnity visualArrow Not working as expected

### ISSUE THREAD

**Issue by haogaobill** [raisimTech/raisimLib#406] opened 2022-12-09 12:26 UTC
Hello Professor,

The visualArrow seems cannot having expected color and orientation. It's always white color no matter what RGB value I passed to addVisualArrow() function. And seems It's not pointing to the correct direction that I wanted. For example, when I use setOrientation(quat) where quat represent the rotational Quaternions that equivalent to Euler angle (0, 0, pi), the arrow is still pointing vertically up, not horizontally w.r.p to world terrain. I'm not sure it's a bug or it's something I did wrong.

**Comment by jhwangbo** [comment] 2022-12-09 20:47
![image](https://user-images.githubusercontent.com/3340750/206793259-176f50ad-4f0b-4ecc-9721-d02030248fea.png)
I could not reproduce your issue. Here is my code to produce the image (except the z-axis which is in identity orientation)

```
  Eigen::Vector4d xDir = {0.70710678118, 0, 0.70710678118, 0};
  Eigen::Vector4d yDir = {0.70710678118, -0.70710678118, 0, 0};
  varrow_x->setOrientation(xDir);
  varrow_y->setOrientation(yDir);
```

If you share your code, I can take a look at it

**Comment by jhwangbo** [comment] 2022-12-09 20:48
BTW, raisim quaternion convention is w,x,y,z

**Comment by jhwangbo** [comment] 2022-12-12 06:53
I am closing this issue until I get further responses

**Closed by jhwangbo** 2022-12-12 06:53 UTC
