### ISSUE TITLE
Mimic Joint Support

### ISSUE THREAD

**Issue by JohannesPankert** [raisimTech/raisimlib#6] opened 2020-10-06 08:20 UTC
Hello,
on the old github page you were stating that mimic joints are soon going to be supported. Are there any updates on that feature?

**Comment by jhwangbo** [comment] 2020-10-06 15:50
duplicate of #1. It seems harder than I thought :( In theory, it's easy but maintaining the efficiency is hard because it breaks 1 body 1 joint assumption.

**Closed by jhwangbo** 2020-10-06 15:50 UTC
