### ISSUE TITLE
rayTest doesn't work well when there are multiple terrains

### ISSUE THREAD

**Issue by jingGM** [raisimTech/raisimLib#277] opened 2022-03-01 06:39 UTC
I spawned 10 HeightMaps overlapped each other using TerrainProperties. When I use rayTest to extract the contacts, it only returns the points contacting with the largest HeightMap.

**Comment by jhwangbo** [comment] 2022-03-07 07:30
What do you mean by "the largest heightmap"? do you mean that it only returns the first contacting point?

**Comment by jingGM** [comment] 2022-03-08 04:36
I created one large heightmap and several small maps on top of it. The elevation of the small maps are obviously higher than the large one. I use rayTest to detect the contacts from top side to the maps, similar to the example. But rayTest only returns the points which are on the largest heightmap. If the ray shoot on small maps, rayTest returns nothing.

**Comment by jhwangbo** [comment] 2022-03-08 04:39
Can you share the screenshots or the code?

**Comment by jhwangbo** [comment] 2022-03-09 02:23
I could not reproduce your issue with my code. I am closing this issue until I get your code

**Closed by jhwangbo** 2022-03-09 02:23 UTC
