### ISSUE TITLE
Segmentation Fault when running examples

### ISSUE THREAD

**Issue by Mr-TonyStark** [raisimTech/raisimLib#130] opened 2021-06-25 05:58 UTC
Hi there,
I recently installed Raisim on Windows10 with a Intel Core i7-8700 CPU. When attempting to run the examples using Developer Command Prompt for VS 2019, I didn't get any feedback. Besides, RaiSimUnity was running but nothing showed on it.
![image](https://user-images.githubusercontent.com/25632781/123371838-0e42fc80-d5b5-11eb-8770-71a792effedd.png)

Then I tried to find out at which part the code whent wrong. I edit the source code at 
`D:\Program Files\RaiSim\raisim_workspace\raisimLib\examples\src\server\robots.cpp` and built it using VS2019 using **Release** x64 configuration. 
Then I found the program stop at this line:
```
 /// create raisim world
    raisim::World world;
```
I found a similar issue here https://github.com/raisimTech/raisimLib/issues/85 except that it's on MacOS, so maybe the real problem is that it cannnot find my activation key.
I tried to place the file activation.raisim at different place, such as 
"D:\Program Files\RaiSim\raisim_workspace\raisimLib\raisim\win32\mt_release\bin\rsc" according to
```
  auto binaryPath = raisim::Path::setFromArgv(argv[0]);
  raisim::World::setActivationKey(binaryPath.getDirectory() + "\\rsc\\activation.raisim");
```
or "D:\Program Files\RaiSim\raisim_workspace\raisimLib\raisim\win32\mt_release\bin" after writing
```
  std::string act = "activation.raisim";
  raisim::World::setActivationKey(act);
```
but it just doesn't work.

**Comment by jhwangbo** [comment] 2021-06-25 06:02
Did you link it against debug libs? There are two versions in the win dir

**Comment by Mr-TonyStark** [comment] 2021-06-25 06:08
> Did you link it against debug libs? There are two versions in the win dir

This issue appeared no matter link it in which way, Release or Debug. The generated exe files stoped at
```
raisim::World world;
```

**Comment by jhwangbo** [comment] 2021-06-25 06:13
How did you link them? Linker tries to find dll in the environment variable Path.

Try to compile it in the release mode and see what happens. If that works, that means your debug build is linked to a release version of raisim

**Comment by Mr-TonyStark** [comment] 2021-06-25 09:03
I tried both debug and release mode but neither of them works. The linker seems to find the lib correctly at compile time, but the execuatable file did not work. I suspect that the libs are not quite compitable with my environment. Can you share me how do you compile those libs? Which compiler do you use?

I tried the following code
[https://drive.google.com/file/d/1CptS7eOnKEQes-NX4OKtAEsp0AU3qAk7/view?usp=sharing](url)
In main2.cpp, the code can run if line 7 and line 8 are comment out. If any one of line 7 and  line 8 exist, it failed.
![image](https://user-images.githubusercontent.com/25632781/123397089-9f759b80-d5d4-11eb-9ff8-fd1073f99b31.png)

**Comment by jhwangbo** [comment] 2021-06-25 09:16
I only test it on MSVC. Do you use something else? As far as I know, windows compilers are not compatible

**Comment by Mr-TonyStark** [comment] 2021-06-25 14:15
> I only test it on MSVC. Do you use something else? As far as I know, windows compilers are not compatible

![image](https://user-images.githubusercontent.com/25632781/123437778-a1565380-d602-11eb-9a38-0c0573254172.png)
I’ve tried these four on VS Code, did you use any one of them?

**Comment by jhwangbo** [comment] 2021-06-25 14:35
It should be amd64.

When you run the examples, did you turn on RaiSimUnity? Do you see something there?

**Comment by Mr-TonyStark** [comment] 2021-06-25 15:28
> It should be amd64.
> 
> When you run the examples, did you turn on RaiSimUnity? Do you see something there?

in the beginning, we do turned on RaiSimUnity. But then we found whether turning RaiSimUnity on or not doesn't bring any difference to me, because the program stoped before using RaiSimUnity.

**Comment by jhwangbo** [comment] 2021-06-25 15:34
What happens if you save the activation key according to https://raisim.com/sections/Installation.html#activation-key and don't call the setActivationKey at all?

**Comment by jhwangbo** [comment] 2021-06-25 21:32
+ When do you see a segmentation fault?

**Comment by Mr-TonyStark** [comment] 2021-06-27 02:24
> What happens if you save the activation key according to https://raisim.com/sections/Installation.html#activation-key and don't call the setActivationKey at all?

In the beginning, I saved the key to according to https://raisim.com/sections/Installation.html#activation-key. In this case, if I don't call the setActivationKey at all, the program will stop at
```
raisim::World world;
```
At this time I compile it in the release mode. If I compile it in the debug mode instead, I will be a segmentation fault.
![image](https://user-images.githubusercontent.com/25632781/123530863-d57c6200-d731-11eb-957d-b0d1ca54a348.png)
> * When do you see a segmentation fault?

**Comment by jhwangbo** [comment] 2021-06-27 02:51
The segfault is just due to MSVC release and debug modes not being compatible with each other. This is normal in MSVC and a serious design flaw. 

What is the exact path to the activation key? Do you have any non latin characters? Can you copy paste it?

**Comment by Mr-TonyStark** [comment] 2021-06-27 05:27
> The segfault is just due to MSVC release and debug modes not being compatible with each other. This is normal in MSVC and a serious design flaw.
> 
> What is the exact path to the activation key? Do you have any non latin characters? Can you copy paste it?

The path is C:\Users\HWY\.raisim\activation.raisim

**Comment by Mr-TonyStark** [comment] 2021-06-28 12:13
After many failed attempts, I finally gave up Windows and turn to Linux. Thank you for your patience.

**Comment by jhwangbo** [comment] 2021-07-27 06:24
I couldn't reproduce this. I'll close this for now. Let me know if you get a clue

**Closed by jhwangbo** 2021-07-27 06:24 UTC
