### ISSUE TITLE
Bug in the reward computation

### ISSUE THREAD

**Issue by weixuanzhang** [raisimTech/raisimLib#131] opened 2021-06-25 10:51 UTC
https://github.com/raisimTech/raisimLib/blob/2717509d5ddcdaa2e463e8a9134b57715cdb41ad/raisimGymTorch/raisimGymTorch/env/VectorizedEnvironment.hpp#L142

Here the agent computes the reward per step. So even in early terminated case you want `reward[agentId] = terminalReward` instead of `reward[agentId] += terminalReward`, right?

**Comment by jhwangbo** [comment] 2021-06-25 11:22
That's right and it is intended that way.  The terminal reward is for early termination only. When it terminates due to timeout, it is not called termination.

**Comment by weixuanzhang** [comment] 2021-06-25 12:04
Hi Jemin,
thanks for the quick response, as always.
I think I am not expressing myself clear enough: in the current code, it is `reward[agentId] += terminalReward`, it appears to me that this line of code uses the reward computed from the previous step plus the terminal reward. Is this the intended way? To me, it is more natural if upon early termination only terminal reward is assigned to the reward vector using `reward[agentId] = terminalReward`

**Comment by jhwangbo** [comment] 2021-06-25 12:40
What you described is not natural to me but you can do that by changing how you set the reward function in ``Environment.hpp``

**Comment by jhwangbo** [comment] 2021-06-26 04:48
I am going to close this issue because it seems like it's not a bug.

**Closed by jhwangbo** 2021-06-26 04:48 UTC
