### ISSUE TITLE
Multi-point contact

### ISSUE THREAD

**Issue by elijahstangerjones** [raisimTech/raisimLib#156] opened 2021-08-09 19:49 UTC
Hi there, 

I want to have a single link with two contact bodies (a foot with a heel and a toe). I want to be able to see the contact force data for each of these individually. My plan was to have two fixed joints in my URDF connected to my foot that each had their own collision box and then use getContacts() to see the force at each point. It seems that raisim does not allow for fixed joints though. 

What is the correct way to get force data for this situation?

**Comment by jhwangbo** [comment] 2021-08-09 20:42
This is a duplicate of #116.
Check this code as well https://github.com/raisimTech/raisimLib/blob/9e4ad0a7b7f90680dbdb49d9051b29f729aa7cdf/raisim/linux/include/raisim/contact/Contact.hpp#L158

**Closed by jhwangbo** 2021-08-09 20:42 UTC

**Comment by elijahstangerjones** [comment] 2021-08-09 21:05
Thanks! 
One question is how to determine which mesh is object A and which mesh is object B? Is the first fixed link added in the URDF become object A?

**Comment by jhwangbo** [comment] 2021-08-09 21:21
No, the order is arbitrary. ObejctA and B are a collision pair. They cannot be on the same body.

**Comment by elijahstangerjones** [comment] 2021-08-09 21:27
Oh so objectA will be one of the collision boxes and objectB will be the ground (or the flip of this)?
How do I determine which collision box on the link (there are two collision objects on the same link)?

**Comment by jhwangbo** [comment] 2021-08-09 21:32
getCollisionBodyA()->name
The name convention is described here https://raisim.com/sections/MaterialSystem.html#id1
