### ISSUE TITLE
Collision between STATIC object and fixed-base object

### ISSUE THREAD

**Issue by weixuanzhang** [raisimTech/raisimLib#52] opened 2021-02-10 15:35 UTC
It seems that when there is a collision between a fixed-base object and the STATIC object, the position outputs NaN. Is this possible? I tried to make the fixed-base object a float-base object. Then the collision works fine.

**Comment by jhwangbo** [comment] 2021-02-10 22:53
There shouldn't be any collision between a static object and a fixed base of a fixed-base articulated system. I tested with the kinova example I sent you and it works fine there. So I don't suspect that is the case.

Can you visualize your example and share it?

**Comment by weixuanzhang** [comment] 2021-02-11 10:39
Thank you very much!
Here are two screen recordings:
1)Every object is floating base except the wall, which is a static object. Everything seems to work fine

https://user-images.githubusercontent.com/8019238/107626194-b9ce5e80-6c5d-11eb-8057-1896ee166cb8.mp4

2) One object is made a fixed-base articulated system (the box). The moment the box touches the wall, it disappears and its position starts to output NaN.

https://user-images.githubusercontent.com/8019238/107626206-bd61e580-6c5d-11eb-8ac0-128a5b5d3134.mp4

**Comment by jhwangbo** [comment] 2021-02-11 11:06
can you share the code and the urdf? You can also just send the files to my email jemin.hwangbo@gmail.com if you don't want to share them with others.

**Comment by jhwangbo** [comment] 2021-02-11 11:33
I couldn't reproduce this with my example.

**Comment by weixuanzhang** [comment] 2021-02-11 11:40
Thanks! The idea behind this fixed-base object is that I want to constrain the robot to a plane to have a 2D simulation first. I suspected also that there is something missing from my urdf file, as I just replaced the robot with kinova_stand and it worked fine with the collision. Here is the code:
[RaisimAerialInteraction-master.zip](https://github.com/raisimTech/raisimLib/files/5964930/RaisimAerialInteraction-master.zip)

**Comment by jhwangbo** [comment] 2021-02-11 14:38
I identify the issue. It is not about the fixed base. There was a corner case in the contact solver that I didn't handle properly. I fixed the problem but I cannot push the change before I carefully check it. I am on holidays now. I will be able to test the change next week when I get back to the lab.

**Comment by weixuanzhang** [comment] 2021-02-11 22:03
Is there a way to avoid this corner case for now? For example, change the shape of the object? Happy lunar new year!

**Comment by jhwangbo** [comment] 2021-02-11 22:32
Do you need the wall? Can you remove it?
Happy new year!

**Comment by jhwangbo** [comment] 2021-02-11 22:51
and do not use a hundred nanogram link mass. use realistic values.

**Comment by weixuanzhang** [comment] 2021-02-12 06:44
>and do not use a hundred nanogram link mass. use realistic values.
Okay. 
I replaced the static wall with a object with large finite mass. And it works for now.

**Comment by jhwangbo** [comment] 2021-02-16 23:48
I pushed a fix for the Linux version. Thx for reporting and testing. Mac and Windows versions will follow

**Closed by jhwangbo** 2021-02-16 23:48 UTC
