### ISSUE TITLE
Foot penetrating into the ground problem

### ISSUE THREAD

**Issue by LALALADA-SPONGEBOB** [raisimTech/raisimLib#371] opened 2022-09-17 00:39 UTC
![image](https://user-images.githubusercontent.com/52847647/190833500-3b52816d-292e-45f6-b85f-c8eb89e6b670.png)

Hi raisimtech!

I am doing an experiment and found some problem related to the robot's foot penetrating into the ground problem.
Why this kind of phenomenon is happening.
The ground is generated through default raisimGymtorch code.(So, Coefficient of restitution is zero)

**Comment by jhwangbo** [comment] 2022-09-19 22:55
What is the time step? can you share a reproducible code?

**Comment by LALALADA-SPONGEBOB** [comment] 2022-09-23 02:22
Since this problem, I have changed my code a lot so it might take a long time to restore my code.
However, to explain briefly, this problem occurred when simulation time step is 0.001 and control_dt is 0.002. Also for step function in environment.hpp code, I integrate once instead of doing it control_dt/simulation_dt times.
If this information is not enough to figure out the problem, I will upload the code later I restore my code.
Thank you in advance

**Comment by jhwangbo** [comment] 2022-10-01 00:32
That is not enough for me. I can run the stress test with this URDF and see if there are penetrations.

**Comment by jhwangbo** [comment] 2022-11-05 06:25
I am closing this because I cannot reproduce it

**Closed by jhwangbo** 2022-11-05 06:25 UTC
