### ISSUE TITLE
'Wrong Message' Errors Occured when using RaiSimUnity

### ISSUE THREAD

**Issue by Wang-Zhicheng** [raisimTech/raisimLib#18] opened 2020-11-19 12:32 UTC
![Screenshot from 2020-11-19 20-20-10](https://user-images.githubusercontent.com/50918255/99665926-3dd0da00-2aa5-11eb-906f-72cd90c5eea4.png)
Hi there.
When using the RaisimUnity to connect to the "anymals" example in the new raisimLib, the client of raisimUnity seems unable to connect to the Server, and a error message showed up in the GUI of RaisimUnity (as the Pic). It says 'the server sends a wrong message.' Also, the server process in the terminal shows "disconnected for 0" every time I click "OK" in the GUI, and the same error shows up again in GUI after a blink.
What does that mean? And how can I fix that?
Hope to be replied, thanks.

**Comment by jhwangbo** [comment] 2020-11-19 12:49
Is this only with "anymals" example? are you using the latest version?

**Comment by Wang-Zhicheng** [comment] 2020-11-20 13:18
I tested other examples in the project, they all showed the same error message.
So I guess there is some kind of mis-configurations.

**Comment by jhwangbo** [comment] 2020-11-20 13:32
The new version shouldn't show that error. can you pull and try again?

**Comment by jhwangbo** [comment] 2020-11-20 13:59
And please check if you are not linking against old libraries. I think this is the most likely issue. Delete all old installations

**Comment by jhwangbo** [comment] 2020-11-23 10:16
Closing this issue until I get feedback. I think the issue is that you didn't delete old installations.

**Closed by jhwangbo** 2020-11-23 10:16 UTC
